const DEFAULT_BOOKS=[{id:'b001',title:'The Great Gatsby',author:'F. Scott Fitzgerald',category:'Classic',color:'#4a7fc1',available:true},{id:'b002',title:'To Kill a Mockingbird',author:'Harper Lee',category:'Classic',color:'#7a4f9a',available:true},{id:'b003',title:'1984',author:'George Orwell',category:'Dystopia',color:'#c9542a',available:false},{id:'b004',title:'Clean Code',author:'Robert C. Martin',category:'Technology',color:'#2a7a50',available:true},{id:'b005',title:'Sapiens',author:'Yuval Noah Harari',category:'History',color:'#8a6520',available:true},{id:'b006',title:'The Alchemist',author:'Paulo Coelho',category:'Fiction',color:'#4a9a8a',available:true},{id:'b007',title:'Atomic Habits',author:'James Clear',category:'Self-Help',color:'#9a4a5a',available:false},{id:'b008',title:'Dune',author:'Frank Herbert',category:'Sci-Fi',color:'#5a7a2a',available:true},{id:'b009',title:'The Pragmatic Programmer',author:'Andrew Hunt',category:'Technology',color:'#3a5a9a',available:true},{id:'b010',title:'Educated',author:'Tara Westover',category:'Memoir',color:'#7a3a6a',available:true},{id:'b011',title:'Thinking Fast and Slow',author:'Daniel Kahneman',category:'Psychology',color:'#2a6a7a',available:true},{id:'b012',title:'The Name of the Wind',author:'Patrick Rothfuss',category:'Fantasy',color:'#6a4a2a',available:false}];

function getBooks(){const d=localStorage.getItem('lib_books');return d?JSON.parse(d):JSON.parse(JSON.stringify(DEFAULT_BOOKS))}
function saveBooks(b){localStorage.setItem('lib_books',JSON.stringify(b))}
function getIssued(){const d=localStorage.getItem('lib_issued');return d?JSON.parse(d):[]}
function saveIssued(i){localStorage.setItem('lib_issued',JSON.stringify(i))}
function isAdmin(){return localStorage.getItem('lib_admin')==='1'}

function init(){if(!localStorage.getItem('lib_books'))saveBooks(DEFAULT_BOOKS);updateStats();renderFeatured();renderBooks();renderIssued();renderSearch();if(isAdmin()&&document.getElementById('section-admin-dashboard').classList.contains('active')){renderAdminBooks();renderAdminIssued()}}

function updateStats(){const b=getBooks();const cats=new Set(b.map(x=>x.category));document.getElementById('stat-total').textContent=b.length;document.getElementById('stat-avail').textContent=b.filter(x=>x.available).length;document.getElementById('stat-issued').textContent=getIssued().length;document.getElementById('stat-cats').textContent=cats.size}

function showSection(name){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById('section-'+name).classList.add('active');document.querySelectorAll('.nav-link').forEach(l=>l.classList.remove('active'));const nl=document.getElementById('nav-'+name);if(nl)nl.classList.add('active');if(name==='books'){populateCatFilter();renderBooks()}if(name==='issued')renderIssued();if(name==='search')doSearch();if(name==='admin-dashboard'){renderAdminBooks();renderAdminIssued()}}

function toggleMenu(){document.getElementById('mobile-menu').classList.toggle('hidden')}

function bookCard(b,ctx){const issued=getIssued().includes(b.id);const el=document.createElement('div');el.className='book-card';el.innerHTML=`<div class="book-cover" style="background:linear-gradient(135deg,${b.color},${darken(b.color)})"><span>${b.title}</span></div><div class="book-info"><h4>${b.title}</h4><p>${b.author}</p><span class="badge ${b.available?'avail':'issued'}">${b.available?'Available':'Issued'}</span><span class="badge cat">${b.category}</span></div><div class="book-actions"><button class="btn-detail" onclick="openModal('${b.id}')">Details</button>${b.available&&!issued?`<button class="btn-issue" onclick="issueBook('${b.id}')">Issue</button>`:issued?`<button class="btn-return" onclick="returnBook('${b.id}')">Return</button>`:'<button class="btn-detail" disabled style="opacity:.5">Unavailable</button>'}</div>`;return el}

function darken(hex){const n=parseInt(hex.slice(1),16);const r=Math.max(0,((n>>16)&255)-60);const g=Math.max(0,((n>>8)&255)-60);const bv=Math.max(0,(n&255)-60);return`#${((1<<24)+(r<<16)+(g<<8)+bv).toString(16).slice(1)}`}

function renderFeatured(){const g=document.getElementById('featured-grid');g.innerHTML='';getBooks().filter(b=>b.available).slice(0,4).forEach(b=>g.appendChild(bookCard(b,'featured')))}

function populateCatFilter(){const sel=document.getElementById('filter-cat');const current=sel.value;sel.innerHTML='<option value="">All Categories</option>';const cats=[...new Set(getBooks().map(b=>b.category))].sort();cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o)});sel.value=current}

function renderBooks(){const g=document.getElementById('books-grid');g.innerHTML='';let b=[...getBooks()];const cat=document.getElementById('filter-cat').value;const sort=document.getElementById('sort-books').value;if(cat)b=b.filter(x=>x.category===cat);if(sort==='title')b.sort((a,c)=>a.title.localeCompare(c.title));else if(sort==='author')b.sort((a,c)=>a.author.localeCompare(c.author));else if(sort==='avail')b.sort((a,c)=>c.available-a.available);b.forEach(x=>g.appendChild(bookCard(x,'books')))}

function doSearch(){const q=document.getElementById('search-input').value.toLowerCase().trim();const g=document.getElementById('search-grid');const em=document.getElementById('search-empty');g.innerHTML='';const b=getBooks().filter(x=>x.title.toLowerCase().includes(q)||x.author.toLowerCase().includes(q)||x.category.toLowerCase().includes(q));if(!q||b.length===0){em.classList.toggle('hidden',!q||b.length>0);b.forEach(x=>g.appendChild(bookCard(x,'search')));return}em.classList.add('hidden');b.forEach(x=>g.appendChild(bookCard(x,'search')))}

function renderIssued(){const g=document.getElementById('issued-grid');const em=document.getElementById('issued-empty');g.innerHTML='';const ids=getIssued();const books=getBooks().filter(b=>ids.includes(b.id));if(books.length===0){em.classList.remove('hidden');return}em.classList.add('hidden');books.forEach(b=>g.appendChild(bookCard(b,'issued')))}

function issueBook(id){const books=getBooks();const b=books.find(x=>x.id===id);if(!b||!b.available)return;const issued=getIssued();if(issued.includes(id))return;b.available=false;saveBooks(books);issued.push(id);saveIssued(issued);updateStats();renderFeatured();renderBooks();renderIssued();doSearch();renderAdminBooks();renderAdminIssued();showToast('📚 "'+b.title+'" issued successfully!');closeModal()}

function returnBook(id){const books=getBooks();const b=books.find(x=>x.id===id);if(!b)return;b.available=true;saveBooks(books);const issued=getIssued().filter(x=>x!==id);saveIssued(issued);updateStats();renderFeatured();renderBooks();renderIssued();doSearch();renderAdminBooks();renderAdminIssued();showToast('✅ "'+b.title+'" returned successfully!');closeModal()}

function openModal(id){const b=getBooks().find(x=>x.id===id);if(!b)return;const issued=getIssued().includes(id);document.getElementById('modal-body').innerHTML=`<div class="modal-cover" style="background:linear-gradient(135deg,${b.color},${darken(b.color)})">${b.title}</div><div class="modal-body-title">${b.title}</div><div class="modal-body-author">by ${b.author}</div><div class="modal-body-cat">Category: ${b.category}</div><div class="modal-body-status"><span class="badge ${b.available?'avail':'issued'}">${b.available?'Available':'Issued'}</span></div>${b.available&&!issued?`<button class="modal-issue-btn" onclick="issueBook('${b.id}')">Issue This Book</button>`:issued?`<button class="modal-return-btn" onclick="returnBook('${b.id}')">Return This Book</button>`:'<p style="color:var(--muted);text-align:center;">This book is currently unavailable.</p>'}`;document.getElementById('modal-overlay').classList.remove('hidden')}

function closeModal(){document.getElementById('modal-overlay').classList.add('hidden')}

function adminLogin(){const u=document.getElementById('admin-user').value;const p=document.getElementById('admin-pass').value;const err=document.getElementById('login-err');if(u==='admin'&&p==='admin123'){localStorage.setItem('lib_admin','1');err.classList.add('hidden');showSection('admin-dashboard');document.getElementById('nav-admin').textContent='Dashboard'}else{err.classList.remove('hidden')}}

function adminLogout(){localStorage.removeItem('lib_admin');document.getElementById('nav-admin').textContent='Admin';showSection('admin-login')}

function dashTab(t){document.querySelectorAll('.dash-panel').forEach(p=>p.classList.add('hidden'));document.querySelectorAll('.dash-nav').forEach(n=>n.classList.remove('active'));document.getElementById('dash-'+t).classList.remove('hidden');document.getElementById('dtab-'+t).classList.add('active');if(t==='books')renderAdminBooks();if(t==='issued')renderAdminIssued()}

function renderAdminBooks(){const c=document.getElementById('admin-books-list');if(!c)return;c.innerHTML='';getBooks().forEach(b=>{const r=document.createElement('div');r.className='admin-book-row';r.innerHTML=`<div class="book-meta"><h4>${b.title}</h4><p>${b.author} · ${b.category}</p></div><span class="badge ${b.available?'avail':'issued'}">${b.available?'Available':'Issued'}</span><div style="display:flex;gap:.5rem"><button class="btn-toggle" onclick="toggleAvail('${b.id}')">Toggle</button><button class="btn-edit" onclick="editBook('${b.id}')">Edit</button><button class="btn-delete" onclick="deleteBook('${b.id}')">Delete</button></div>`;c.appendChild(r)})}

function renderAdminIssued(){const c=document.getElementById('admin-issued-list');if(!c)return;c.innerHTML='';const ids=getIssued();if(ids.length===0){c.innerHTML='<p style="color:var(--muted)">No books currently issued.</p>';return}const books=getBooks();ids.forEach(id=>{const b=books.find(x=>x.id===id);if(!b)return;const r=document.createElement('div');r.className='issued-row';r.innerHTML=`<div class="book-meta"><h4>${b.title}</h4><p>${b.author} · ${b.category}</p></div><button class="btn-return btn-toggle" onclick="returnBook('${b.id}')">Return</button>`;c.appendChild(r)})}

function toggleAvail(id){const b=getBooks();const book=b.find(x=>x.id===id);if(!book)return;book.available=!book.available;if(book.available){const issued=getIssued().filter(x=>x!==id);saveIssued(issued)}saveBooks(b);updateStats();renderAdminBooks();renderAdminIssued();renderBooks();renderFeatured();showToast('Status updated for "'+book.title+'"')}

function deleteBook(id){if(!confirm('Delete this book?'))return;const b=getBooks().filter(x=>x.id!==id);saveBooks(b);const issued=getIssued().filter(x=>x!==id);saveIssued(issued);updateStats();renderAdminBooks();renderAdminIssued();renderBooks();renderFeatured();showToast('Book deleted.')}

function editBook(id){const b=getBooks().find(x=>x.id===id);if(!b)return;dashTab('add');document.getElementById('form-title').textContent='Edit Book';document.getElementById('f-id').value=b.id;document.getElementById('f-title').value=b.title;document.getElementById('f-author').value=b.author;document.getElementById('f-cat').value=b.category;document.getElementById('f-cover').value=b.color;document.getElementById('f-avail').value=String(b.available)}

function saveBook(){const id=document.getElementById('f-id').value;const title=document.getElementById('f-title').value.trim();const author=document.getElementById('f-author').value.trim();const cat=document.getElementById('f-cat').value.trim();const color=document.getElementById('f-cover').value.trim()||'#4a7fc1';const avail=document.getElementById('f-avail').value==='true';if(!title||!author||!cat){showToast('⚠️ Please fill all required fields.');return}const books=getBooks();if(id){const b=books.find(x=>x.id===id);if(b){b.title=title;b.author=author;b.category=cat;b.color=color;b.available=avail}saveBooks(books);showToast('Book updated!')}else{const nb={id:'b'+Date.now(),title,author,category:cat,color,available:avail};books.push(nb);saveBooks(books);showToast('Book added!')}resetForm();updateStats();renderAdminBooks();renderBooks();renderFeatured();populateCatFilter()}

function resetForm(){document.getElementById('form-title').textContent='Add New Book';['f-id','f-title','f-author','f-cat','f-cover'].forEach(f=>document.getElementById(f).value='');document.getElementById('f-avail').value='true'}

function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(window._toastTimer);window._toastTimer=setTimeout(()=>t.classList.add('hidden'),3000)}

document.addEventListener('DOMContentLoaded',()=>{init();if(isAdmin()){document.getElementById('nav-admin').textContent='Dashboard'}});